import { InventoryItem, Category } from './types';

// Data extracted from Cheonan Water Purification Center PDF (2025.01)
// Split Name and Standard
export const initialData: InventoryItem[] = [
  {
    id: "ELEC-001",
    category: Category.ELECTRIC,
    name: "MCCB 배선용차단기",
    standard: "630A 4P",
    model: "ABS 604C",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 1,
    safeStock: 1,
    location: "전기실 A",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-002",
    category: Category.ELECTRIC,
    name: "MCCB 배선용차단기",
    standard: "400A 4P",
    model: "ABS 404C",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 1,
    safeStock: 1,
    location: "전기실 A",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-003",
    category: Category.ELECTRIC,
    name: "MCCB 배선용차단기",
    standard: "250A 4P",
    model: "ABS 204C ZCT",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 3,
    safeStock: 2,
    location: "전기실 B",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-004",
    category: Category.ELECTRIC,
    name: "MCCB 배선용차단기",
    standard: "225A 4P",
    model: "ABS 204C",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 0,
    safeStock: 2,
    location: "자재창고",
    note: "발주 필요",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-010",
    category: Category.ELECTRIC,
    name: "MCCB 배선용차단기",
    standard: "100A 4P",
    model: "ABS 104C",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 1,
    safeStock: 1,
    location: "자재창고",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-020",
    category: Category.ELECTRIC,
    name: "MCCB 배선용차단기",
    standard: "600A 3P",
    model: "HiBS 603",
    manufacturer: "현대",
    unit: "EA",
    currentStock: 2,
    safeStock: 2,
    location: "전기실 C",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-030",
    category: Category.ELECTRIC,
    name: "누전차단기",
    standard: "30A 4P",
    model: "EBS 54c",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 0,
    safeStock: 5,
    location: "자재창고",
    note: "재고 없음",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-040",
    category: Category.ELECTRIC,
    name: "릴레이",
    standard: "24VDC 8P",
    model: "LY2N",
    manufacturer: "OMRON",
    unit: "EA",
    currentStock: 8,
    safeStock: 10,
    location: "계측기실",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-041",
    category: Category.ELECTRIC,
    name: "릴레이",
    standard: "200/220VAC 14P",
    model: "SMY4SL",
    manufacturer: "KOINO",
    unit: "EA",
    currentStock: 62,
    safeStock: 30,
    location: "계측기실",
    note: "입고 80, 출고 26",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-050",
    category: Category.ELECTRIC,
    name: "타이머",
    standard: "220VDC",
    model: "AT8N",
    manufacturer: "AUTONICS",
    unit: "EA",
    currentStock: 4,
    safeStock: 5,
    location: "자재창고",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-060",
    category: Category.ELECTRIC,
    name: "PUSH BOTTON",
    standard: "220VAC Ø25",
    model: "AL22 적색",
    manufacturer: "미기재",
    unit: "EA",
    currentStock: 21,
    safeStock: 20,
    location: "자재창고 2열",
    note: "",
    lastUpdated: "2025-01-01"
  },
  {
    id: "ELEC-070",
    category: Category.ELECTRIC,
    name: "전자식모터보호계전기",
    standard: "22A",
    model: "GMP22-2PA",
    manufacturer: "LS",
    unit: "EA",
    currentStock: 2,
    safeStock: 2,
    location: "전기실 A",
    note: "",
    lastUpdated: "2025-01-01"
  }
];